
apiVersion: v1
kind: Pod
metadata:
  name: demo-keycloak-init-container
spec:
  containers:
    - image: quay.io/keycloak/keycloak-init-container:master
      imagePullPolicy: Always
      name: extensions-init
      command: ['sleep',  'infinity']
      env:
        - name: KEYCLOAK_EXTENSIONS
          value: https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar,https://gitlab.com/BeToken/ocp-themes/-/raw/main/theme.jar
      volumeMounts:
        - mountPath: /opt/extensions
          name: keycloak-extensions
  volumes:
    - emptyDir: {}
      name: keycloak-extensions

      #   - env:
      #     - name: KEYCLOAK_EXTENSIONS
      #       value: https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar,https://gitlab.com/BeToken/ocp-themes/-/raw/main/theme.jar
      #   image: quay.io/keycloak/keycloak-init-container:master
      #   imagePullPolicy: Always
      #   name: extensions-init
      #   volumeMounts:
      #   - mountPath: /opt/extensions
      #     name: keycloak-extensions
      # restartPolicy: Always
      # volumes:
      # - name: sso-x509-https-secret
      #   secret:
      #     defaultMode: 420
      #     optional: true
      #     secretName: sso-x509-https-secret
      # - emptyDir: {}
      #   name: keycloak-extensions

